name: "機能追加・修正テンプレート"
description: "機能追加、バグ修正、リファクタリング用のテンプレート"
labels: []
body:
  - type: textarea
    id: summary
    attributes:
      label: "概要"
      description: "このIssueの目的と内容を1-2行で簡潔に示す"
      placeholder: |
        〇〇の処理を改善し、パフォーマンスを向上させる
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: "現状の問題"
      description: "解決すべき問題点を具体的に記述（コード箇所、影響、重大度など）"
      placeholder: |
        ### 問題1: 〇〇（重大度: HIGH）

        **場所**: `path/to/file.py:行番号`

        ```python
        # 問題のあるコード
        ```

        **問題**: なぜこれが問題なのか

        ---

        ### 問題2: △△（重大度: MEDIUM）
        ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "実装（修正）案"
      description: "どのように解決するか、具体的なアプローチを記述"
      placeholder: |
        ### 採用する手段

        〇〇を使用して△△を実現する

        ```python
        # 実装例
        ```

        ### 変更対象ファイル

        | ファイル | 変更内容 |
        |---------|---------|
        | `path/to/file.py` | 〇〇の追加 |
    validations:
      required: true

  - type: textarea
    id: why-this-approach
    attributes:
      label: "なぜこの手段を選んだか"
      description: "選択した手段のメリットや選定理由を記述"
      placeholder: |
        1. **〇〇との親和性**: 既存の△△と相性が良い
        2. **運用性**: 設定が簡単で保守しやすい
        3. **公式推奨**: ドキュメントで推奨されている方式

  - type: textarea
    id: why-not-others
    attributes:
      label: "なぜ他の手段を選ばなかったか"
      description: "検討したが却下した代替案とその理由"
      placeholder: |
        | 代替案 | 却下理由 |
        |--------|---------|
        | 方式A | コストが高い、運用負荷が大きい |
        | 方式B | セキュリティリスクがある |
        | 方式C | 要件を満たさない |

  - type: textarea
    id: implementation-plan
    attributes:
      label: "実装計画"
      description: "具体的な実装ステップを記述"
      placeholder: |
        ### Step 1: 〇〇の準備

        ```python
        # コード例
        ```

        ### Step 2: △△の実装

        - ポイント1
        - ポイント2

        ### Step 3: テストの追加

  - type: textarea
    id: expected-effect
    attributes:
      label: "期待される効果"
      description: "この変更による改善効果を記述"
      placeholder: |
        - 〇〇が改善される
        - △△のリスクが軽減される
        - ユーザーが□□できるようになる

  - type: textarea
    id: testing
    attributes:
      label: "テスト"
      description: "追加・修正するテストの内容"
      placeholder: |
        ### 単体テスト

        - [ ] `test_〇〇.py`: 正常系テスト
        - [ ] `test_〇〇.py`: 異常系テスト（エラーハンドリング）

        ### 結合テスト

        - [ ] APIエンドポイントの動作確認
        - [ ] 既存テストの通過確認

  - type: textarea
    id: input-output
    attributes:
      label: "入力と出力"
      description: "変更前後の入出力、または期待するリクエスト/レスポンスを記述"
      placeholder: |
        ### 変更対象ファイル

        | ファイル | 変更内容 |
        |---------|---------|
        | `path/to/file.py` | 〇〇の修正 |

        ### 入力（修正前の状態）

        ```
        現在の動作や設定
        ```

        ### 出力（修正後の期待動作）

        ```
        期待する動作や設定
        ```

  - type: textarea
    id: done-criteria
    attributes:
      label: "完了条件"
      description: "このIssueが完了したと言える条件をチェックリストで記述"
      placeholder: |
        - [ ] 〇〇の実装が完了
        - [ ] △△のテストが追加され、通過
        - [ ] 既存テストが全て通過
        - [ ] ドキュメントの更新（該当する場合）
        - [ ] コードレビュー完了
    validations:
      required: true

  - type: textarea
    id: related
    attributes:
      label: "関連Issue・リンク"
      description: "関連するIssue、PR、ドキュメントなどのリンク"
      placeholder: |
        - #123 関連するIssue
        - [公式ドキュメント](https://example.com)
